name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      test:
        description: test
        required: true
        type: string
      target:
        description: 'True to print to STDOUT'
        required: true
        type: boolean

  repository_dispatch:
    types: [sample]

jobs:
  step1:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.test }} == 'go'
    steps:
      - uses: actions/checkout@master
      - run: echo ${{ github.event.inputs.test }}
  
  step2:
    runs-on: ubuntu-latest
    if: ${{ inputs.target }} 
    steps:
      - run: echo step2
  
  step3:
    runs-on: ubuntu-latest
    if: ${{ github.event.client_payload.flg }}
    steps:
      - run: echo step3
