name: Manually triggered workflow
on:
  workflow_dispatch:

jobs:
  step1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          echo "Hello ${{ github.event.inputs.name }}!"
          echo "- in ${{ github.event.inputs.home }}!"
  step2:
    runs-on: ubuntu-latest
    needs: step1 
    steps:
      - run: |
          echo step2
