name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      test:
        description: test
        required: true
        type: string
      target:
        description: 'True to print to STDOUT'
        required: true
        type: boolean

jobs:
  step1:
    if: ${{ inputs.test }} == 'go'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: echo step1
  step2:
    if: ${{ inputs.print_tags }} 
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo step2
