name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: test
        options: 
        - 'true'
        - 'false'

jobs:
  step1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          echo ${{ github.event.inputs.target }}
  step2:
    if: ${{ github.event.inputs.target }} == 'true'
    runs-on: ubuntu-latest
    needs: step1 
    steps:
      - run: |
          echo step2
