name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: test
        options: 
        - "true"
        - "false"

jobs:
  step1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          echo step1
  step2:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.target == "true" }}
    needs: step1 
    steps:
      - run: |
          echo step2
