name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      test:
        description: test
        required: true
        type: string
      target:
        description: 'True to print to STDOUT'
        required: true
        type: boolean

jobs:
  step1:
    runs-on: ubuntu-latest
    if: ${{ inputs.test }} == 'go'
    steps:
      - uses: actions/checkout@master
      - run: echo ${{ inputs.test }}
  step2:
    runs-on: ubuntu-latest
    if: ${{ inputs.print_tags }} 
    steps:
      - run: echo step2
