name: Sample workflow
on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: 選んで
        options: 
        - mt_regression_dev_new
        - mt_regression_dev_new_singin
  repository_dispatch:
    types: [test_result]
jobs:
  step:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          echo "${{ github.event.inputs.target }}${{ github.event.client_payload.tag_name }}"
