name: Sample workflow
run-name: "${{ github.event.client_payload.description }}"
on:
  repository_dispatch:
    types: [mabl_slack_command]
jobs:
  step:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          echo "${{ github.event.inputs.target }}${{ github.event.client_payload.tag_name }}"
