name: Sample workflow
on:
  workflow_dispatch:
jobs:
  step:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          echo "Hello ${{ github.event.inputs.name }}!"
