name: Sample workflow
on:
  workflow_dispatch:
  repository_dispatch:
    types: [test_result]
jobs:
  step:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          if: ${{ github.event.client_payload.tag_name}} = "":
            echo "workflow"
          if: ${{ github.event.client_payload.tag_name}} != "":
            echo "${{ github.event.client_payload.tag_name }}"
