name: Sample workflow
on:
  workflow_dispatch:
  repository_dispatch:
    types: [test_result]
jobs:
  step:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: |
          echo "${{ github.event.client_payload.tag_name }}!"
