name: OWASP ZAP Actions
on:
  repository_dispatch:
jobs:
  website-scan:
    runs-on: ubuntu-latest
    name: DAST (Dynamic Application Security Testing)
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Action Full Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          #token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: zaproxy/zap-stable
          target: https://www.example.com
          cmd_options: >
            -a
            -j
            -z "
            -config alert.maxInstances=0
            -config view.locale=ja_JP
            "
